### ISSUE TITLE
Refactor Package & make it more consistent.

### ISSUE THREAD

**Issue by payam-zahedi** [persian-tools/dart-persian-tools#12]
Since all the features of the package are now available, I think we need a refactoring to make everything more consistent.
We should word on following tasks:
1. core feature dart file should have the name of the feature.
  - if the name of the feature is `commas` the file name should have a name of `commas.dart`.
2. all the models classes should implement in the `model.dart` file.
3. all the constant for the specific feature should move to `lib/src/constants/feature_name/constants.dart` file.
4. Values that are not used as public APIs must be converted to private access.

**Comment by payam-zahedi** [comment]
@EhsanAramide  @m-khooryani If you are interested, you can do one of the tasks defined in our [current project](https://github.com/persian-tools/dart-persian-tools/projects/1).  If you have any suggestion for this issue please leave comment and let me know.

**Comment by makhosravi** [comment]
Hi
I'd like to contribute to refactoring.

**Comment by payam-zahedi** [comment]
Ok khosro, so I will assign you to this issue.

**Comment by EhsanAramide** [comment]
Is refactoring ended or not?
@makhosravi 
@payam-zahedi

**Comment by makhosravi** [comment]
Hi,
I'm working on it and will be ready soon

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi  for code, doc, example and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for code, doc, example and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for code, doc, example and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for code

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for review
