### ISSUE TITLE
Add document for uncommented functions and features

### ISSUE THREAD

**Issue by payam-zahedi** [persian-tools/dart-persian-tools#14]
For better usage experience we need to write documentation for our package. The first priority is with core methods that are used publicly.

**Comment by ali-master** [comment]
Good news, I appreciate it.

**Comment by payam-zahedi** [comment]
@EhsanAramide as the refactor issue and PR has been merged, you can start your work on this issue.

**Comment by payam-zahedi** [comment]
@all-contributors please add @EhsanAramide  for code

**Comment by payam-zahedi** [comment]
@all-contributors please add @EhsanAramide for code, doc, example, maintenance, review and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for code, doc, example and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @makhosravi for code, doc and test

**Comment by payam-zahedi** [comment]
@all-contributors please add @ali-master for ideas, maintenance and projectManagement
