### ISSUE TITLE
not Support 0900 & 0996    BUG

### ISSUE THREAD

**Issue by akbarrahmani** [persian-tools/dart-persian-tools#34]
سلام این دو شماره موبایل رو که من بهش برخوردم رو ساپورت نمیکنه
0900
0996
و علاوه بر اون اپراتورهای جدید مثل آپتل و سامانتل هم هستند که پشتیبانی نمیشومد!

**Comment by payam-zahedi** [comment]
سلام اکبر ممنون بابت ایشو ای که باز کردی.
 من سعی میکنم تو تغطیلاتم این شماره ها رو اضافه کنم.

**Comment by payam-zahedi** [comment]
@akbarrahmani
 اطلاعی داری که شماره 0996 مال کدوم شهره اطلاعات دقیقی درموردش نیست تو اینترنت

**Comment by payam-zahedi** [comment]
@ali-master 
شما در این مورد اطلاعاتی داری؟

**Comment by akbarrahmani** [comment]
@payam-zahedi
@ali-master 
سلام
 ۰۹۹۶ فکر میکنم سراسر هست همراه اوب
و ۰۹۰۰ هم ایرانسل دایمی سراسری

**Comment by payam-zahedi** [comment]
@akbarrahmani 

درسته انجامش دادم میتونی ورژن جدید رو دریافت کنی و تست کنی
https://pub.dev/packages/persian_tools/changelog

**Comment by payam-zahedi** [comment]
در مورد اپراتور های آپتل و سامانتل هم اگر لینکی داری همینجا برامون بزار که انجامش بدیم

**Comment by akbarrahmani** [comment]
https://www.aptel.ir
https://www.samantel.ir

**Comment by ali-master** [comment]
> @ali-master 
> شما در این مورد اطلاعاتی داری؟
> 

منم اطلاعی ندارم حقیقا

**Comment by payam-zahedi** [comment]
این ایژو رو فعلا میبندیم و اگر لازم بود میتونید بازش کنید.
