### ISSUE TITLE
Participation request

### ISSUE THREAD

**Issue by makhosravi** [persian-tools/dart-persian-tools#8]
Hi
I'm Mohammad Ali and would like to participate in development of this repository, "numbers to words" feature.

**Comment by payam-zahedi** [comment]
Hi @makhosravi, I hope you're doing well. 
I'm glad to hear that you would like to work on this project.
You can start your Participation. Check the source code and if you need anything please let me know.

**Comment by payam-zahedi** [comment]
To begin:
1. you can `clone` the project.
2. run it on your IDE.
3. create the new branch with related feature name, something like `number-to-word`.
4. implement the feature.
5. and create  your  PR.

**Comment by ali-master** [comment]
> To begin:
> 1. you can `clone` the project.
> 2. run it on your IDE.
> 3. create the new branch with related feature name, something like `number-to-word`.
> 4. implement the feature.
> 5. and create  your  PR.

For the Branch name, please follow this convention
https://dev.to/couchcamote/git-branching-name-convention-cch

And for the commit messages, please follow this convention 
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by makhosravi** [comment]
Thank you for your guidance and approval
